//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraEntites
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CaraEntities : DbContext
    {
        public CaraEntities()
            : base("name=CaraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Country> Countries { get; set; }
        public DbSet<UserToConfirm> UserToConfirms { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<FilmAltTitle> FilmAltTitles { get; set; }
        public DbSet<Participant> Participants { get; set; }
        public DbSet<PasswordToReset> PasswordToResets { get; set; }
        public DbSet<EmailNote> EmailNotes { get; set; }
        public DbSet<Format> Formats { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<PostScreeningAction> PostScreeningActions { get; set; }
        public DbSet<Screener> Screeners { get; set; }
        public DbSet<ScreenerGenre> ScreenerGenres { get; set; }
        public DbSet<Attribute> Attributes { get; set; }
        public DbSet<ScreenerAttribute> ScreenerAttributes { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<CertificateMailing> CertificateMailings { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyContact> CompanyContacts { get; set; }
        public DbSet<ContactRole> ContactRoles { get; set; }
        public DbSet<RelType> RelTypes { get; set; }
        public DbSet<RightsType> RightsTypes { get; set; }
        public DbSet<FilmSubmission> FilmSubmissions { get; set; }
        public DbSet<CompanyRightsType> CompanyRightsTypes { get; set; }
    }
}
