//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyContact
    {
        public int ContactID { get; set; }
        public int CompanyID { get; set; }
        public int FilmSubmissionId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MidName { get; set; }
        public string Suffix { get; set; }
        public int AddressID { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string eMail { get; set; }
        public int RoleId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
        public virtual ContactRole ContactRole { get; set; }
    }
}
