//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRightsType
    {
        public int CompanyRightsTypeId { get; set; }
        public int FilmSubmissionId { get; set; }
        public int CompanyId { get; set; }
        public int RightsTypeId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual FilmSubmission FilmSubmission { get; set; }
        public virtual RightsType RightsType { get; set; }
    }
}
