//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactRole
    {
        public ContactRole()
        {
            this.CompanyContacts = new HashSet<CompanyContact>();
        }
    
        public int ContactRoleID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CompanyContact> CompanyContacts { get; set; }
    }
}
