//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailsToConfirm
    {
        public int ConfirmEmailId { get; set; }
        public int UserId { get; set; }
        public string Code { get; set; }
        public System.DateTime Created { get; set; }
        public string ConfirmedIP { get; set; }
        public Nullable<System.DateTime> Confirmed { get; set; }
    
        public virtual User User { get; set; }
    }
}
