//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int FilmId { get; set; }
        public string Ttitle { get; set; }
        public int UserId { get; set; }
        public string ISAN { get; set; }
        public string ISANCheck { get; set; }
        public string EIDR { get; set; }
        public string OtherID { get; set; }
        public string Synopsis { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> Submitted { get; set; }
        public Nullable<System.DateTime> AcceptedByCARA { get; set; }
        public Nullable<System.DateTime> ReturnedByCARA { get; set; }
    
        public virtual User User { get; set; }
    }
}
