//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Format
    {
        public Format()
        {
            this.Screeners = new HashSet<Screener>();
        }
    
        public int FormatId { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<Screener> Screeners { get; set; }
    }
}
