//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToConfirm
    {
        public int UserToConfirmId { get; set; }
        public int UserId { get; set; }
        public string CodeForEmail { get; set; }
        public Nullable<System.DateTime> EmailConfirmed { get; set; }
        public Nullable<System.DateTime> CaraApproved { get; set; }
        public string CaraApprovedBy { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual User User { get; set; }
    }
}
