//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaraEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhone
    {
        public int UserPhoneId { get; set; }
        public int UserId { get; set; }
        public string PhoneTypeCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
    
        public virtual User User { get; set; }
    }
}
